platform :android do
  lane :internal do
    build()

    supply(
      aab: "build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: "internal"
    )
  end

  lane :build do
    Dir.chdir("..") do
      sh "flutter", "pub", "get"
      sh "flutter", "build", "appbundle"
    end
  end
end
